# docker-compose.yml
version: '3.8'

services:
  database:
    image: postgres:13
    environment:
      POSTGRES_DB: cafeconnect
      POSTGRES_USER: cafeuser
      POSTGRES_PASSWORD: cafepass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  gameserver:
    build: .
    ports:
      - "7777:7777/udp"
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://cafeuser:cafepass@database:5432/cafeconnect
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - gameserver

volumes:
  postgres_data:
